# Generated by Django 5.2.17 on 2026-09-20 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('romantic', 'Romantic Gesture'), ('sympathy', 'Sympathy'), ('celebration', 'Celebration'), ('thank_you', 'Thank You')], max_length=20)),
                ('style', models.CharField(choices=[('romantic', 'Romantic'), ('elegant', 'Elegant'), ('modern', 'Modern & Minimal'), ('rustic', 'Rustic'), ('cheerful', 'Cheerful & Bright')], max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('card_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('ordered', 'Ordered')], default='draft', max_length=10)),
                ('source', models.CharField(choices=[('custom', 'Custom'), ('ai', 'AI')], default='custom', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greeting_card', models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'greeting-cards'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BouquetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bouquets.bouquet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_items', to='catalog.item')),
            ],
            options={
                'unique_together': {('bouquet', 'item')},
            },
        ),
    ]
