# Generated by Django 5.2.17 on 2026-09-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
        ('bouquets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='ai_recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_as_bouquet', to='ai_recommendations.airecommendation'),
        ),
    ]
