# Generated by Django 5.2.17 on 2026-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_recommendations/'),
        ),
    ]
