# Generated by Django 5.2.17 on 2026-09-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0002_airecommendation_generated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='occasion',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('romantic', 'Romantic Gesture'), ('sympathy', 'Sympathy'), ('celebration', 'Celebration'), ('thank_you', 'Thank You')], max_length=20),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='style',
            field=models.CharField(choices=[('romantic', 'Romantic'), ('elegant', 'Elegant'), ('modern', 'Modern & Minimal'), ('rustic', 'Rustic'), ('cheerful', 'Cheerful & Bright')], max_length=20),
        ),
    ]
